version: '3.8'

services:
  postgres-sales:
    image: postgres:15-alpine
    container_name: postgres-sales
    environment:
      POSTGRES_DB: erp_sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_sales_data:/var/lib/postgresql/data
    networks:
      - erp-net
    restart: unless-stopped

  sales-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-sales:5432/erp_sales
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    volumes:
      # Menghubungkan folder uploads di dalam kontainer ke folder lokal proyek Anda
      - ./uploads:/app/uploads
    depends_on:
      - postgres-sales
    networks:
      - erp-net
    restart: unless-stopped

volumes:
  postgres_sales_data:

networks:
  erp-net:
    external: true
    name: erp-net